services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@devops.com"
      PGADMIN_DEFAULT_PASSWORD: "qwe"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  app:
    image: golang:1.22
    command:
      - go
      - run
      - main.go
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres